### ISSUE TITLE
hello ~!

### ISSUE THREAD

**Issue by neosys131** [hsreina/DJMax-editor#1]
i am using this program, it's very helpful 
but i have 2 problems !
problem 1 : how can i use moving long note?
problem 2 : how do i unpack and repack djmax technika pak files?

if you can solve above 2 of problems, i would willing to donate you even $300 !

have a nice day !

**Comment by hsreina** [comment]
For the problem 1 :
You just need to put notes with attr 90 like this on a related track
![image](https://cloud.githubusercontent.com/assets/7342613/22394230/2db5cbf0-e4e8-11e6-8a22-ce07fe1ed75c.png)

The four 1st track are player notes
The four next just under seem to affect visible notes.
I'll try to add icons and name to those notes for the next version. 
We need a documentation on how to create each notes. It depend between all DJMax version
Technika, Trilogy, Cyclon.
1st I focus on T3 then next maybe one compatible with multiple versions

For the problem 2 :
I need to think about it. If you were able to read a pt files from T3 that mean you unpacked it right?

**Comment by neosys131** [comment]
hello !
i can not get PT files from technika 3.
but i would like to get unlocking tool.
also 
![asdf](https://cloud.githubusercontent.com/assets/25397305/22395866/f58e43fa-e58d-11e6-9763-fbf80d1ba6b5.png)
can you make option likes this?
up and down note option. up part and down part to have different color and note is reversed !
also it will be great to have preview like djmax technika game.

**Comment by hsreina** [comment]
What is "unlocking tool"?
You want me to display "up" and "down"?
I think you'll must adapt yourself to the editor because it will be generic for all *.pt files. not just Technika.
Everything in the editor is based on the pt file not on the gameplay of the game.
But maybe a kind of preview will maybe be possible.

**Comment by neosys131** [comment]
hello !
i mean 'unpacking' tools.
maybe you can add up and down as 'Option' so ppl can
choose display up and down or not.
i been trying to make a pattern but it was so confusing.
yeap. preview would help a lot.
but i hope this will show up and down as option.

**Comment by neosys131** [comment]
can you make play option where i placed. when i press play button, i always start from 0:00.
make a option to play sounds and notes where i am located (for ex 1:20 or something)

**Comment by hsreina** [comment]
About the play button, I have to think about it. I can cheat a little but the main song is played as a note.
If i keep the context of editor of pt files, I'm not supposed to know it was a song but just a note.
So if you start the song from any place, you'll maybe lost the volume set at the beginning and other options.

**Comment by neosys131** [comment]
hi, i just found another bug.
when i press play button then stop.
it will keep on playing MR ogg file !

**Comment by hsreina** [comment]
Should be fixed in the new version http://download.shadosoft-tm.com/djmax/DJMaxEditor.zip
